[package]
name = "dispendik_compare"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
calamine = "0.18.0"
console = "0.15.1"
csv = "1.1.6"
glob = "0.3.0"
similar = "2.2.0"
